export enum BusinessErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  TOO_MANY_REQUESTS_ERROR = 'TOO_MANY_REQUESTS_ERROR',
  ENTITY_CREATION_ERROR = 'ENTITY_CREATION_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
}
